const User = require("../models/userModel.js")
const Recipes = require("../models/recipesModel.js")
const RecipeDetails = require("../models/recipesModel.js")
const Ingredients = require("../models/ingredientsModel.js")



Recipes.bulkCreate([

  {Name: 'Lasagne'},
  {Name: 'Potatismos'},
  {Name: 'Soppa'}
])

Ingredients.bulkCreate([
  { Name: "Asparagus" },
  { Name: "Broccoli" },
  { Name: "Carrots" },
  { Name: "Cauliflower" },
  { Name: "Celery" },
  { Name: "Corn" },
  { Name: "Cucumbers" },
  { Name: "Lettuce " },
  { Name: "Mushrooms" },
  { Name: "Onions" },
  { Name: "Peppers" },
  { Name: "Potatoes" },
  { Name: "Spinach" },
  { Name: "Squash" },
  { Name: "Zucchini" },
  { Name: "Tomatoes" },
  { Name: "Fresh fruits" },
  { Name: "Apples" },
  { Name: "Avocados" },
  { Name: "Bananas" },
  { Name: "Berries" },
  { Name: "Cherries" },
  { Name: "Grapefruit" },
  { Name: "Grapes" },
  { Name: "Kiwis" },
  { Name: "Melon" },
  { Name: "Oranges" },
  { Name: "Peaches" },
  { Name: "Nectarines" },
  { Name: "Pears" },
  { Name: "Plums" },
  { Name: "Bagels" },
  { Name: "Chip dip" },
  { Name: "English muffins" },
  { Name: "Eggs / Fake eggs" },
  { Name: "Fruit juice" },
  { Name: "Hummus" },
  { Name: "Ready-bake breads" },
  { Name: "Tofu" },
  { Name: "Tortillas" },
  { Name: "Burritos" },
  { Name: "Fish sticks" },
  { Name: "Ice cream" },
  { Name: "Sorbet" },
  { Name: "Popsicles" },
  { Name: "Fries" },
  { Name: "BBQ sauce" },
  { Name: "Gravy" },
  { Name: "Honey" },
  { Name: "Hot sauce" },
  { Name: "Jam" },
  { Name: "Ketchup" },
  { Name: "Mustard" },
  { Name: "Mayonnaise" },
  { Name: "Relish" },
  { Name: "Salad dressing" },
  { Name: "Salsa" },
  { Name: "Soy sauce" },
  { Name: "Steak sauce" },
  { Name: "Syrup" },
  { Name: "Worcestershire sauce" },
  { Name: "Bouillon cubes" },
  { Name: "Cereal" },
  { Name: "Coffee" },
  { Name: "Lemons" },
  { Name: "Limes" },
  { Name: "Olive oil" },
  { Name: "Pancake Mix" },
  { Name: "Waffle mix" },
  { Name: "Pasta" },
  { Name: "Peanut butter" },
  { Name: "Pickles" },
  { Name: "Rice" },
  { Name: "Tea" },
  { Name: "Vegetable oil" },
  { Name: "Vinegar" },
  { Name: "Applesauce" },
  { Name: "Baked beans" },
  { Name: "Chili" },
  { Name: "Fruit" },
  { Name: "Olives" },
  { Name: "Tinned meats" },
  { Name: "Canned Tuna" },
  { Name: "Veggies" },
  { Name: "Basil" },
  { Name: "Black pepper" },
  { Name: "Cilantro" },
  { Name: "Cinnamon" },
  { Name: "Garlic" },
  { Name: "Ginger" },
  { Name: "Mint" },
  { Name: "Oregano" },
  { Name: "Paprika" },
  { Name: "Parsley" },
  { Name: "Red pepper" },
  { Name: "Salt" },
  { Name: "Spice mix" },
  { Name: "Vanilla extract" },
  { Name: "Butter" },
  { Name: "Margarine" },
  { Name: "Cottage cheese" },
  { Name: "Milk" },
  { Name: "Sour cream" },
  { Name: "Whipped cream" },
  { Name: "Yogurt" },
  { Name: "Cheese" },
  { Name: "Bleu cheese" },
  { Name: "Cheddar" },
  { Name: "Cream cheese" },
  { Name: "Feta" },
  { Name: "Goat cheese" },
  { Name: "Mozzarella" },
  { Name: "Parmesan" },
  { Name: "Provolone" },
  { Name: "Ricotta" },
  { Name: "Swiss Cheese" },
  { Name: "Bacon" },
  { Name: "Sausage" },
  { Name: "Beef" },
  { Name: "Chicken" },
  { Name: "Ground beef" },
  { Name: "Turkey" },
  { Name: "Ham" },
  { Name: "Hot dogs, YEAH!" },
  { Name: "Catfish" },
  { Name: "Crab" },
  { Name: "Lobster" },
  { Name: "Mussels" },
  { Name: "Oysters" },
  { Name: "Salmon" },
  { Name: "Shrimp" },
  { Name: "Tilapia" },
  { Name: "Tuna" },
  { Name: "Cod" },
  { Name: "Beer" },
  { Name: "Club soda" },
  { Name: "Champagne" },
  { Name: "Gin" },
  { Name: "Juice" },
  { Name: "Mixers" },
  { Name: "Red wine" },
  { Name: "White wine" },
  { Name: "Rum" },
  { Name: "Saké" },
  { Name: "Soda pop" },
  { Name: "Sports drink" },
  { Name: "Whiskey" },
  { Name: "Vodka" },
  { Name: "Croissants" },
  { Name: "Buns" },
  { Name: "Cake" },
  { Name: "Cookies" },
  { Name: "Donuts" },
  { Name: "Fresh bread" },
  { Name: "Sliced bread" },
  { Name: "Pie! Pie! Pie!" },
  { Name: "Pita bread" },
  { Name: "Baking powder" },
  { Name: "Baking soda" },
  { Name: "Bread crumbs" },
  { Name: "Cake Mix" },
  { Name: "Chocolate chips" },
  { Name: "Cocoa" },
  { Name: "Flour" },
  { Name: "Sugar" },
  { Name: "Sugar substitute" },
  { Name: "Yeast" },
  { Name: "Crackers" },
  { Name: "Dried fruit" },
  { Name: "Granola bars" },
  { Name: "Nuts" },
  { Name: "Seeds" },
  { Name: "Oatmeal" },
  { Name: "Popcorn" },
  { Name: "Potato chips" },
  { Name: "Pretzels" }
]
)

// const db = require("./connection")

// db.run(`INSERT INTO Ingredients ("Name")
// VALUES
// ("Asparagus"),
// ("Broccoli"),
// ("Carrots"),
// ("Cauliflower"),
// ("Celery"),
// ("Corn"),
// ("Cucumbers"),
// ("Lettuce "),
// ("Mushrooms"),
// ("Onions"),
// ("Peppers"),
// ("Potatoes"),
// ("Spinach"),
// ("Squash"),
// ("Zucchini"),
// ("Tomatoes"),
// ("Fresh fruits"),
// ("Apples"),
// ("Avocados"),
// ("Bananas"),
// ("Berries"),
// ("Cherries"),
// ("Grapefruit"),
// ("Grapes"),
// ("Kiwis"),
// ("Melon"),
// ("Oranges"),
// ("Peaches"),
// ("Nectarines"),
// ("Pears"),
// ("Plums"),
// ("Bagels"),
// ("Chip dip"),
// ("English muffins"),
// ("Eggs / Fake eggs"),
// ("Fruit juice"),
// ("Hummus"),
// ("Ready-bake breads"),
// ("Tofu"),
// ("Tortillas"),
// ("Burritos"),
// ("Fish sticks"),
// ("Ice cream"),
// ("Sorbet"),
// ("Popsicles"),
// ("Fries"),
// ("BBQ sauce"),
// ("Gravy"),
// ("Honey"),
// ("Hot sauce"),
// ("Jam"),
// ("Ketchup"),
// ("Mustard"),
// ("Mayonnaise"),
// ("Relish"),
// ("Salad dressing"),
// ("Salsa"),
// ("Soy sauce"),
// ("Steak sauce"),
// ("Syrup"),
// ("Worcestershire sauce"),
// ("Bouillon cubes"),
// ("Cereal"),
// ("Coffee"),
// ("Lemons"),
// ("Limes"),
// ("Olive oil"),
// ("Pancake Mix"),
// ("Waffle mix"),
// ("Pasta"),
// ("Peanut butter"),
// ("Pickles"),
// ("Rice"),
// ("Tea"),
// ("Vegetable oil"),
// ("Vinegar"),
// ("Applesauce"),
// ("Baked beans"),
// ("Chili"),
// ("Fruit"),
// ("Olives"),
// ("Tinned meats"),
// ("Canned Tuna"),
// ("Veggies"),
// ("Basil"),
// ("Black pepper"),
// ("Cilantro"),
// ("Cinnamon"),
// ("Garlic"),
// ("Ginger"),
// ("Mint"),
// ("Oregano"),
// ("Paprika"),
// ("Parsley"),
// ("Red pepper"),
// ("Salt"),
// ("Spice mix"),
// ("Vanilla extract"),
// ("Butter"),
// ("Margarine"),
// ("Cottage cheese"),
// ("Milk"),
// ("Sour cream"),
// ("Whipped cream"),
// ("Yogurt"),
// ("Cheese"),
// ("Bleu cheese"),
// ("Cheddar"),
// ("Cream cheese"),
// ("Feta"),
// ("Goat cheese"),
// ("Mozzarella"),
// ("Parmesan"),
// ("Provolone"),
// ("Ricotta"),
// ("Swiss Cheese"),
// ("Bacon"),
// ("Sausage"),
// ("Beef"),
// ("Chicken"),
// ("Ground beef"),
// ("Turkey"),
// ("Ham"),
// ("Hot dogs, YEAH!"),
// ("Catfish"),
// ("Crab"),
// ("Lobster"),
// ("Mussels"),
// ("Oysters"),
// ("Salmon"),
// ("Shrimp"),
// ("Tilapia"),
// ("Tuna"),
// ("Cod"),
// ("Beer"),
// ("Club soda"),
// ("Champagne"),
// ("Gin"),
// ("Juice"),
// ("Mixers"),
// ("Red wine"),
// ("White wine"),
// ("Rum"),
// ("Saké"),
// ("Soda pop"),
// ("Sports drink"),
// ("Whiskey"),
// ("Vodka"),
// ("Croissants"),
// ("Buns"),
// ("Cake"),
// ("Cookies"),
// ("Donuts"),
// ("Fresh bread"),
// ("Sliced bread"),
// ("Pie! Pie! Pie!"),
// ("Pita bread"),
// ("Baking powder"),
// ("Baking soda"),
// ("Bread crumbs"),
// ("Cake Mix"),
// ("Chocolate chips"),
// ("Cocoa"),
// ("Flour"),
// ("Sugar"),
// ("Sugar substitute"),
// ("Yeast"),
// ("Crackers"),
// ("Dried fruit"),
// ("Granola bars"),
// ("Nuts"),
// ("Seeds"),
// ("Oatmeal"),
// ("Popcorn"),
// ("Potato chips"),
// ("Pretzels")

// `, (err)=>{

//     err&& console.log(err)
// })
